### ISSUE TITLE
Feature idea: ability to view HTML file without saving to a file

### ISSUE THREAD

**Issue by svisser** [vividvilla/csvtotable#6]
It would be nice if this tool could be used without having to delete the HTML file afterwards (when you're done reviewing the CSV file).

For example, you'd run `csvtotable my_file.csv --view` (or similar) and view the HTML page in your browser directly without writing it to a file (similar to how you can run a webserver by doing `python -m http.server 8000`).

**Comment by vividvilla** [comment]
This is a great idea. I will implement this in next few releases.

**Comment by chfw** [comment]
what about webbrowser.open('/tmp/goog.html')? I don't think there is a need for a http server.

**Comment by vividvilla** [comment]
Added this feature in release [v1.1.2](https://github.com/vividvilla/csvtotable/releases/tag/1.1.2).

@chfw Using `webbrowser` was the most logical solution instead of serving in http server. So I am creating a file inside temp folder created by python `tempfile` module and keeping the file open till keyboard interrupt exception is raised. You can [refer the function here](https://github.com/vividvilla/csvtotable/blob/master/csvtotable/convert.py#L73).

**Comment by svisser** [comment]
@vividvilla many thanks for adding this feature!
